ALTER TABLE debtorsmaster ADD COLUMN address5 VARCHAR( 20 );
 ALTER TABLE debtorsmaster ADD COLUMN address6 VARCHAR( 15 );
ALTER TABLE custbranch ADD COLUMN braddress5 VARCHAR( 20 );
ALTER TABLE custbranch  ADD COLUMN braddress6 VARCHAR( 15 );
ALTER TABLE custbranch ADD COLUMN brpostaddr5 VARCHAR( 20 ); 
ALTER TABLE custbranch ADD COLUMN brpostaddr6 VARCHAR( 15 );
UPDATE custbranch SET braddress5='', braddress6='', brpostaddr5='', brpostaddr6='';
UPDATE debtorsmaster SET address5='', address6='';
ALTER TABLE custbranch ALTER COLUMN braddress5  SET DEFAULT ''::text;
ALTER TABLE custbranch ALTER COLUMN braddress6  SET DEFAULT ''::text;
ALTER TABLE custbranch ALTER COLUMN brpostaddr5  SET DEFAULT ''::text;
ALTER TABLE custbranch ALTER COLUMN brpostaddr6  SET DEFAULT ''::text;
ALTER TABLE debtorsmaster ALTER COLUMN address5  SET DEFAULT ''::text;
ALTER TABLE debtorsmaster ALTER COLUMN address6  SET DEFAULT ''::text;
ALTER TABLE locations ADD COLUMN deladd4 VARCHAR(40);
ALTER TABLE locations ALTER  COLUMN deladd4 SET  DEFAULT ''::text;
ALTER TABLE locations ADD COLUMN deladd5 VARCHAR(20);
ALTER TABLE locations ALTER  COLUMN deladd5 SET  DEFAULT ''::text;
ALTER TABLE locations ADD COLUMN deladd6 VARCHAR(15);
ALTER TABLE locations ALTER  COLUMN deladd6 SET  DEFAULT ''::text;
ALTER TABLE purchorders ADD COLUMN deladd5 VARCHAR(20);
ALTER TABLE purchorders ALTER  COLUMN deladd5 SET  DEFAULT ''::text;
ALTER TABLE purchorders ADD COLUMN deladd6 VARCHAR(15);
ALTER TABLE purchorders ALTER  COLUMN deladd6 SET  DEFAULT ''::text;
ALTER TABLE purchorders ADD COLUMN contact VARCHAR(30);
ALTER TABLE purchorders ALTER  COLUMN contact SET  DEFAULT ''::text;
ALTER TABLE recurringsalesorders ADD COLUMN deladd5 VARCHAR(20);
ALTER TABLE recurringsalesorders ALTER  COLUMN deladd5 SET  DEFAULT ''::text;
ALTER TABLE recurringsalesorders ADD COLUMN deladd6 VARCHAR(15);
ALTER TABLE recurringsalesorders ALTER  COLUMN deladd6 SET  DEFAULT ''::text;
ALTER TABLE salesorders ADD COLUMN deladd5 VARCHAR(20);
ALTER TABLE salesorders ALTER  COLUMN deladd5 SET  DEFAULT ''::text;
ALTER TABLE salesorders ADD COLUMN deladd6 VARCHAR(20);
ALTER TABLE salesorders ALTER  COLUMN deladd6 SET  DEFAULT ''::text;
ALTER TABLE suppliers ADD COLUMN address5 VARCHAR(20);
ALTER TABLE suppliers ALTER  COLUMN address5 SET  DEFAULT ''::text;
ALTER TABLE suppliers ADD COLUMN address6 VARCHAR(20);
ALTER TABLE suppliers ALTER  COLUMN address6 SET  DEFAULT ''::text;
ALTER TABLE companies  RENAME COLUMN regoffice3 TO regoffice4;
ALTER TABLE companies  RENAME COLUMN regoffice2 TO regoffice3;
ALTER TABLE companies  RENAME COLUMN regoffice1 TO regoffice2;
ALTER TABLE companies  RENAME COLUMN postaladdress TO regoffice1;
ALTER TABLE companies ADD COLUMN regoffice5 VARCHAR(20);
ALTER TABLE companies ALTER  COLUMN regoffice5 SET  DEFAULT ''::text;
ALTER TABLE companies ADD COLUMN regoffice6 VARCHAR(15);
ALTER TABLE companies ALTER  COLUMN regoffice6 SET  DEFAULT ''::text;
