ALTER TABLE debtorsmaster ADD COLUMN address5 VARCHAR( 20 );
 ALTER TABLE debtorsmaster ADD COLUMN address6 VARCHAR( 15 );
ALTER TABLE custbranch ADD COLUMN braddress5 VARCHAR( 20 );
ALTER TABLE custbranch  ADD COLUMN braddress6 VARCHAR( 15 );
ALTER TABLE custbranch ADD COLUMN brpostaddr5 VARCHAR( 20 ); 
ALTER TABLE custbranch ADD COLUMN brpostaddr6 VARCHAR( 15 );
UPDATE custbranch SET braddress5='', braddress6='', brpostaddr5='', brpostaddr6='';
UPDATE debtorsmaster SET address5='', address6='';
ALTER TABLE custbranch ALTER COLUMN braddress5 SET NOT NULL;
ALTER TABLE custbranch ALTER COLUMN braddress6 SET NOT NULL;
ALTER TABLE custbranch ALTER COLUMN brpostaddr5 SET NOT NULL;
ALTER TABLE custbranch ALTER COLUMN brpostaddr6 SET NOT NULL;
ALTER TABLE debtorsmaster ALTER COLUMN address5 SET NOT NULL;
ALTER TABLE debtorsmaster ALTER COLUMN address6 SET NOT NULL;
ALTER TABLE custbranch ALTER COLUMN braddress5  SET DEFAULT ''::text;
ALTER TABLE custbranch ALTER COLUMN braddress6  SET DEFAULT ''::text;
ALTER TABLE custbranch ALTER COLUMN brpostaddr5  SET DEFAULT ''::text;
ALTER TABLE custbranch ALTER COLUMN brpostaddr6  SET DEFAULT ''::text;
ALTER TABLE debtorsmaster ALTER COLUMN address5  SET DEFAULT ''::text;
ALTER TABLE debtorsmaster ALTER COLUMN address6  SET DEFAULT ''::text;
