<?php
/* $Revision: 1.7 $ */
?>
<BR><BR><BR>
				</td>
		    </tr>
		</table>

        </td>
        <td background="css/default/images/outline/r.gif" colspan="3" align="right" valign="top"><img src="css/default/images/outline/tr.gif" width="10" height="10" alt="" /></td>
    </tr>
    <tr>
        <td background="css/default/images/outline/r.gif" width="10"><img src="css/default/images/outline/r.gif" width="10" height="10" alt="" /></td>
    </tr>
    <tr>
        <td background="css/default/images/outline/bm.gif"><img src="css/default/images/outline/bl.gif" width="10" height="10" alt="" /></td>
        <td background="css/default/images/outline/bm.gif"><img src="css/default/images/outline/bm.gif" width="10" height="10" alt="" /></td>
        <td width="10"><img src="css/default/images/outline/br.gif" width="10" height="10" alt="" /></td>
    </tr>
</table>
<font size=2><?php echo date("l " . $DefaultDateFormat . " | g:i A") ?></font>
<table align="center" id="footer">
	<tr>
		<td align="center" class="footer"><?php echo $CompanyName;?></td>
	</tr>
	<tr>
		<td align="center">
			<a href="http://www.weberp.org" target="_blank">
			<img src="<?php echo $rootpath . '/css/' . $theme . '/images/webERP+sm.gif'; ?>" border=0>
			</a>
		</td>
	</tr>
	<tr>
		<td align="center" class="footer">webERP <?php echo _('Copyright'); ?> &copy; Logic Works Ltd</td>
	</tr>
</table>

</body>
</html>
