<?php

/* Define error codes that are returned by api functions*/
	define('NoAuthorisation', 1);
	define('IncorrectDebtorNumberLength', 1000);
	define('DebtorNoAlreadyExists', 1001);
	define('IncorrectDebtorNameLength', 1002);
	define('InvalidAddressLine', 1003);
	define('CurrencyCodeNotSetup', 1004);
	define('SalesTypeNotSetup', 1005);
	define('InvalidClientSinceDate', 1006);
	define('HoldReasonNotSetup', 1007);
	define('PaymentTermsNotSetup', 1008);
	define('InvalidDiscount', 1009);
	define('InvalidPaymentDiscount', 1010);
	define('InvalidLastPaid', 1011);
	define('InvalidLastPaidDate', 1012);
	define('InvalidCreditLimit', 1013);
	define('InvalidInvAddrBranch', 1014);
	define('InvalidDiscountCode', 1015);
	define('InvalidEDIInvoices', 1016);
	define('InvalidEDIOrders', 1017);
	define('InvalidEDIReference', 1018);
	define('InvalidEDITransport', 1019);
	define('InvalidEDIAddress', 1020);
	define('InvalidEDIServerUser', 1021);
	define('InvalidEDIServerPassword', 1022);
	define('InvalidTaxRef', 1023);
	define('InvalidCustomerPOLine', 1024);
	define('DatabaseUpdateFailed', 1025);
	define('NoDebtorNumber', 1026);
	define('DebtorDoesntExist', 1027);
	define('IncorrectBranchNumberLength', 1028);
	define('BranchNoAlreadyExists', 1029);
	define('IncorrectBranchNameLength', 1030);
	define('InvalidEstDeliveryDays', 1031);
	define('AreaCodeNotSetup', 1032);
	define('SalesmanCodeNotSetup', 1033);
	define('InvalidFwdDate', 1034);
	define('InvalidPhoneNumber', 1035);
	define('InvalidFaxNumber', 1036);
	define('InvalidContactName', 1037);
	define('InvalidEmailAddress', 1038);
	define('LocationCodeNotSetup', 1039);
	define('TaxGroupIdNotSetup', 1040);
	define('ShipperNotSetup', 1041);
	define('InvalidDeliverBlind', 1042);
	define('InvalidDisableTrans', 1043);
	define('InvalidSpecialInstructions', 1044);
	define('InvalidCustBranchCode', 1045);
	define('BranchNoDoesntExist', 1046);
	define('StockCodeDoesntExist', 1047);
	define('StockCategoryDoesntExist', 1048);
	define('IncorrectStockDescriptionLength', 1049);
	define('IncorrectUnitsLength', 1050);
	define('IncorrectMBFlag', 1051);
	define('InvalidCurCostDate', 1052);
	define('InvalidActualCost', 1053);
	define('InvalidLowestLevel', 1054);
	define('InvalidDiscontinued', 1055);
	define('InvalidEOQ', 1056);
	define('InvalidVolume', 1057);
	define('InvalidKgs', 1058);
	define('IncorrectBarCodeLength', 1059);
	define('IncorrectDiscountCategory', 1060);
	define('TaxCategoriesDoesntExist', 1061);
	define('InvalidSerialised', 1062);
	define('InvalidPerishable', 1064);
	define('InvalidDecmalPlaces', 1065);
	define('IncorrectLongStockDescriptionLength', 1066);
	define('StockCodeAlreadyExists', 1067);
	define('TransactionNumberAlreadyExists', 1068);
	define('InvalidTranDate', 1069);
	define('InvalidSettled', 1070);
	define('IncorrectReference', 1071);
	define('IncorrectTpe', 1072);
	define('InvalidOrderNumbers', 1073);
	define('InvalidExchangeRate', 1074);
	define('InvalidOVAmount', 1075);
	define('InvalidOVGst', 1076);
	define('InvalidOVFreight', 1077);
	define('InvalidDiffOnExchange', 1078);
	define('InvalidAllocation', 1079);
	define('IncorrectInvoiceText', 1080);
	define('InvalidShipVia', 1081);
	define('InvalidEdiSent', 1082);
	define('InvalidConsignment', 1083);
	define('InvalidLastCost', 1084);
	define('InvalidMaterialCost', 1085);
	define('InvalidLabourCost', 1086);
	define('InvalidOverheadCost', 1087);
	define('InvalidCustomerRef', 1088);
	define('InvalidBuyerName', 1089);
	define('InvalidComments', 1090);
	define('InvalidOrderDate', 1091);
	define('InvalidDeliverTo', 1092);
	define('InvalidFreightCost', 1094);
	define('InvalidDeliveryDate', 1095);
	define('InvalidQuotationFlag', 1096);
	define('OrderHeaderNotSetup', 1097);
	define('InvalidUnitPrice', 1098);
	define('InvalidQuantity', 1099);
	define('InvalidDiscountPercent', 1100);
	define('InvalidNarrative', 1101);
	define('InvalidItemDueDate', 1102);
	define('InvalidPOLine', 1103);
	define('GLAccountCodeAlreadyExists', 1104);
	define('IncorrectAccountNameLength', 1105);
	define('AccountGroupDoesntExist', 1106);
	define('GLAccountSectionAlreadyExists', 1107);
	define('IncorrectSectionNameLength', 1108);
	define('GLAccountGroupAlreadyExists', 1109);
	define('GLAccountSectionDoesntExist', 1110);
	define('InvalidPandL', 1111);
	define('InvalidSequenceInTB', 1112);
	define('GLAccountGroupDoesntExist', 1113);
	define('InvalidLatitude', 1114);
	define('InvalidLongitude', 1115);
	define('CustomerTypeNotSetup', 1116);
	define('NoPricesSetup', 1117);
	define('InvalidInvoicedQuantity', 1118);
	define('InvalidActualDispatchDate', 1119);
	define('InvalidCompletedFlag', 1120);
	define('InvalidCategoryID', 1121);
	define('InvalidCategoryDescription', 1122);
	define('InvalidStockType', 1123);
	define('GLAccountCodeDoesntExists', 1124);
	define('StockCategoryAlreadyExists', 1125);
	define('SupplierNoAlreadyExists', 1126);
	define('IncorrectSupplierNameLength', 1127);
	define('InvalidSupplierSinceDate', 1128);
	define('InvalidBankAccount', 1129);
	define('InvalidBankReference', 1130);
	define('InvalidBankPartics', 1131);
	define('InvalidRemittanceFlag', 1132);
	define('FactorCompanyNotSetup', 1133);
	define('SupplierNoDoesntExists', 1134);
	define('InvalidSuppliersUOM', 1135);
	define('InvalidConversionFactor', 1136);
	define('InvalidSupplierDescription', 1137);
	define('InvalidLeadTime', 1138);
	define('InvalidPreferredFlag', 1139);
	define('StockSupplierLineDoesntExist', 1140);
	define('InvalidRequiredByDate', 1141);
	define('InvalidStartDate', 1142);
	define('InvalidCostIssued', 1143);
	define('InvalidQuantityRequired', 1144);
	define('InvalidQuantityReceived', 1145);
	define('InvalidStandardCost', 1146);
	define('IncorrectSerialNumber', 1147);
	define('WorkOrderDoesntExist', 1148);
	define('InvalidIssuedQuantity', 1149);
	define('InvalidTransactionDate', 1150);
	define('InvalidReceivedQuantity', 1151);
	define('ItemNotControlled', 1152);
	define('ItemSerialised', 1153);
	define('BatchNumberDoesntExist', 1154);
	define('BatchIsEmpty', 1155);
	define('NoSuchArea', 1156);
	define('NoSuchSalesMan', 1157);
	define('NoCompanyRecord',1158);
	define('NoReadOrder',1159);
	define('NoReadOrderLines',1160);
	define('NoTaxProvince',1161);
	define('TaxRatesFailed',1162);
	define('NoReadCustomerBranch',1163);
	define('NoReadItem',1164);
	define('MustBeReceiptOrCreditNote',1165);
	define('NoTransactionToAllocate',1166);
    define('InvalidOVDiscount',1167);
    define('IncorrectLocationCodeLength',1168);
    define('LocationCodeAlreadyExists',1169);
    define('LocationCodeDoesntExist',1170);
    define('IncorrectLocationNameLength',1171);
    define('TaxProvinceIdNotSetup',1172);
    define('InvalidControlled',1173);


/* Array of Descriptions of errors */
	$ErrorDescription['1'] = _('No Authorisation');
	$ErrorDescription['1000'] = _('Incorrect Debtor Number Length');
	$ErrorDescription['1001'] = _('Debtor No Already Exists');
	$ErrorDescription['1002'] = _('Incorrect Debtor Name Length');
	$ErrorDescription['1003'] = _('Invalid Address Line');
	$ErrorDescription['1004'] = _('Currency Code Not Setup');
	$ErrorDescription['1005'] = _('Sales Type Not Setup');
	$ErrorDescription['1006'] = _('Invalid Client Since Date');
	$ErrorDescription['1007'] = _('Hold Reason Not Setup');
	$ErrorDescription['1008'] = _('Payment Terms Not Setup');
	$ErrorDescription['1009'] = _('Invalid Discount');
	$ErrorDescription['1010'] = _('Invalid Payment Discount');
	$ErrorDescription['1011'] = _('Invalid Last Paid');
	$ErrorDescription['1012'] = _('Invalid Last Paid Date');
	$ErrorDescription['1013'] = _('Invalid Credit Limit');
	$ErrorDescription['1014'] = _('Invalid Inv Address Branch');
	$ErrorDescription['1015'] = _('Invalid Discount Code');
	$ErrorDescription['1016'] = _('Invalid EDI Invoices');
	$ErrorDescription['1017'] = _('Invalid EDI Orders');
	$ErrorDescription['1018'] = _('Invalid EDI Reference');
	$ErrorDescription['1019'] = _('Invalid EDI Transport');
	$ErrorDescription['1020'] = _('Invalid EDI Address');
	$ErrorDescription['1021'] = _('Invalid EDI Server User');
	$ErrorDescription['1022'] = _('Invalid EDI Server Password');
	$ErrorDescription['1023'] = _('Invalid Tax Reference');
	$ErrorDescription['1024'] = _('Invalid CustomerPOLine');
	$ErrorDescription['1025'] = _('Database Update Failed');
	$ErrorDescription['1026'] = _('No Debtor Number');
	$ErrorDescription['1027'] = _('Debtor Does not Exist');
	$ErrorDescription['1028'] = _('Incorrect Branch Number Length');
	$ErrorDescription['1029'] = _('Branch No Already Exists');
	$ErrorDescription['1030'] = _('Incorrect Branch Name Length');
	$ErrorDescription['1031'] = _('Invalid Est Delivery Days');
	$ErrorDescription['1032'] = _('Area Code Not Setup');
	$ErrorDescription['1033'] = _('Salesman Code Not Setup');
	$ErrorDescription['1034'] = _('Invalid Fwd Date');
	$ErrorDescription['1035'] = _('Invalid Phone Number');
	$ErrorDescription['1036'] = _('Invalid Fax Number');
	$ErrorDescription['1037'] = _('Invalid Contact Name');
	$ErrorDescription['1038'] = _('Invalid Email Address');
	$ErrorDescription['1039'] = _('Location Code Not Setup');
	$ErrorDescription['1040'] = _('Tax Group Id Not Setup');
	$ErrorDescription['1041'] = _('Shipper Not Setup');
	$ErrorDescription['1042'] = _('Invalid Deliver Blind');
	$ErrorDescription['1043'] = _('Invalid Disable Transactions');
	$ErrorDescription['1044'] = _('Invalid Special Instructions');
	$ErrorDescription['1045'] = _('Invalid Customer Branch Code');
	$ErrorDescription['1046'] = _('Branch No Does not Exist');
	$ErrorDescription['1047'] = _('Stock Code Does not Exist');
	$ErrorDescription['1048'] = _('Stock Category Does not Exist');
	$ErrorDescription['1049'] = _('Incorrect Stock Description Length');
	$ErrorDescription['1050'] = _('Incorrect Units Length');
	$ErrorDescription['1051'] = _('Incorrect MB Flag');
	$ErrorDescription['1052'] = _('Invalid Current Cost Date');
	$ErrorDescription['1053'] = _('Invalid Actual Cost');
	$ErrorDescription['1054'] = _('Invalid Lowest Level');
	$ErrorDescription['1055'] = _('Invalid Discontinued');
	$ErrorDescription['1056'] = _('Invalid EOQ');
	$ErrorDescription['1057'] = _('Invalid Volume');
	$ErrorDescription['1058'] = _('Invalid Kgs');
	$ErrorDescription['1059'] = _('Incorrect BarCode Length');
	$ErrorDescription['1060'] = _('Incorrect Discount Category');
	$ErrorDescription['1061'] = _('Tax Category Does not Exist');
	$ErrorDescription['1062'] = _('Invalid Serialised');
	$ErrorDescription['1063'] = _('Incorrect Append File');
	$ErrorDescription['1064'] = _('Invalid Perishable');
	$ErrorDescription['1065'] = _('Invalid Decimal Places');
	$ErrorDescription['1066'] = _('Incorrect Long Stock Description Length');
	$ErrorDescription['1067'] = _('Stock Code Already Exists');
	$ErrorDescription['1068'] = _('Transaction Number Already Exists');
	$ErrorDescription['1069'] = _('Invalid Transaction Date');
	$ErrorDescription['1070'] = _('Invalid Settled');
	$ErrorDescription['1071'] = _('Incorrect Reference');
	$ErrorDescription['1072'] = _('Incorrect TPE');
	$ErrorDescription['1073'] = _('Invalid Order Numbers');
	$ErrorDescription['1074'] = _('Invalid Exchange Rate');
	$ErrorDescription['1075'] = _('Invalid OV Amount');
	$ErrorDescription['1076'] = _('Invalid OV Gst');
	$ErrorDescription['1077'] = _('Invalid OV Freight');
	$ErrorDescription['1078'] = _('Invalid Diff On Exchange');
	$ErrorDescription['1079'] = _('Invalid Allocation');
	$ErrorDescription['1080'] = _('Incorrect Invoice Text');
	$ErrorDescription['1081'] = _('Invalid Ship Via');
	$ErrorDescription['1082'] = _('Invalid Edi Sent');
	$ErrorDescription['1083'] = _('Invalid Consignment');
	$ErrorDescription['1084'] = _('Invalid Last Cost');
	$ErrorDescription['1085'] = _('Invalid Material Cost');
	$ErrorDescription['1086'] = _('Invalid Labour Cost');
	$ErrorDescription['1087'] = _('Invalid Overhead Cost');
	$ErrorDescription['1088'] = _('Invalid Customer Reference');
	$ErrorDescription['1089'] = _('Invalid Buyer Name');
	$ErrorDescription['1090'] = _('Invalid Comments');
	$ErrorDescription['1091'] = _('Invalid Order Date');
	$ErrorDescription['1092'] = _('Invalid Delivery Name');
	$ErrorDescription['1094'] = _('Invalid Freight Cost');
	$ErrorDescription['1095'] = _('Invalid Delivery Date');
	$ErrorDescription['1096'] = _('Invalid Quotation Flag');
	$ErrorDescription['1097'] = _('Order header not setup');
	$ErrorDescription['1098'] = _('Invalid unit cost');
	$ErrorDescription['1099'] = _('Invalid Quantity');
	$ErrorDescription['1100'] = _('Invalid Discount Percent');
	$ErrorDescription['1101'] = _('Invalid Narrative');
	$ErrorDescription['1102'] = _('Invalid Item Due');
	$ErrorDescription['1103'] = _('Invalid PO line');
	$ErrorDescription['1104'] = _('GL account code already exists');
	$ErrorDescription['1105'] = _('GL account code name is incorrect length');
	$ErrorDescription['1106'] = _('GL account group does not exist');
	$ErrorDescription['1107'] = _('GL account section already exists');
	$ErrorDescription['1108'] = _('GL account section name is incorrect length');
	$ErrorDescription['1109'] = _('GL account group already exists');
	$ErrorDescription['1110'] = _('GL account section does not exist');
	$ErrorDescription['1111'] = _('Invalid profit and loss flag');
	$ErrorDescription['1112'] = _('Invalid sequenceintb figure');
	$ErrorDescription['1113'] = _('GL account group does not exist');
	$ErrorDescription['1114'] = _('Invalid Latitude figure');
	$ErrorDescription['1115'] = _('Invalid Longitude figure');
	$ErrorDescription['1116'] = _('Customer type not set up');
	$ErrorDescription['1117'] = _('No sales prices setup');
	$ErrorDescription['1118'] = _('Invalid invoiced quantity');
	$ErrorDescription['1119'] = _('Invalid actual dispatch date');
	$ErrorDescription['1120'] = _('Invalid completed flag');
	$ErrorDescription['1121'] = _('Invalid category id');
	$ErrorDescription['1122'] = _('Invalid category description');
	$ErrorDescription['1123'] = _('Invalid stock type');
	$ErrorDescription['1124'] = _('GL account code does not exist');
	$ErrorDescription['1125'] = _('Stock category already exists');
	$ErrorDescription['1126'] = _('Supplier code already exists');
	$ErrorDescription['1127'] = _('Incorrect supplier name length, or supplier name does not exist');
	$ErrorDescription['1128'] = _('Incorrect supplier since date');
	$ErrorDescription['1129'] = _('Incorrect bank account');
	$ErrorDescription['1130'] = _('Incorrect bank reference');
	$ErrorDescription['1131'] = _('Incorrect bank partics');
	$ErrorDescription['1132'] = _('Incorrect remittance flags');
	$ErrorDescription['1133'] = _('Factor company not set up');
	$ErrorDescription['1134'] = _('Supplier does not exist');
	$ErrorDescription['1135'] = _('Incorrect suppliers UOM');
	$ErrorDescription['1136'] = _('Incorrect conversion factor');
	$ErrorDescription['1137'] = _('Incorrect supplier description');
	$ErrorDescription['1138'] = _('Invalid Lead time');
	$ErrorDescription['1139'] = _('Invalid Preferred flag');
	$ErrorDescription['1140'] = _('StockID SupplierID line does not exist');
	$ErrorDescription['1141'] = _('Invalid Required By Date');
	$ErrorDescription['1142'] = _('Invalid Start Date');
	$ErrorDescription['1143'] = _('Invalid Cost Issued');
	$ErrorDescription['1144'] = _('Invalid Quantity Required');
	$ErrorDescription['1145'] = _('Invalid Quantity Received');
	$ErrorDescription['1146'] = _('Invalid Standard Cost');
	$ErrorDescription['1147'] = _('Invalid Serial Number or Lot Reference');
	$ErrorDescription['1148'] = _('Work order number does not exist');
	$ErrorDescription['1149'] = _('Invalid issued quantity');
	$ErrorDescription['1150'] = _('Invalid transaction date');
	$ErrorDescription['1151'] = _('Invalid received quantity');
	$ErrorDescription['1152'] = _('Stock item is not controlled');
	$ErrorDescription['1153'] = _('Stock item is serialised');
	$ErrorDescription['1154'] = _('Batch number does not exist');
	$ErrorDescription['1155'] = _('Batch is empty');
	$ErrorDescription['1156'] = _('No such area');
	$ErrorDescription['1157'] = _('No such salesman');
	$ErrorDescription['1158'] = _('Unable to read company record');
	$ErrorDescription['1159'] = _('Unable to read sales order');
	$ErrorDescription['1160'] = _('Unable to read sales order lines');
	$ErrorDescription['1161'] = _('Unable to get tax province of location');
	$ErrorDescription['1162'] = _('Unable to read tax rates for this item and tax group');
	$ErrorDescription['1163'] = _('Unable to read customer and branch details');
	$ErrorDescription['1164'] = _('Unable to read credit note item details');
	$ErrorDescription['1165'] = _('Can only allocate receipts or a credit notes');
	$ErrorDescription['1166'] = _('No transaction found to allocate');
    $ErrorDescription['1167'] = _('Invalid OV Discount');
    $ErrorDescription['1168'] = _('Incorrect Location Code Length');
    $ErrorDescription['1169'] = _('Location Code Already Exists');
    $ErrorDescription['1170'] = _('Location Code Does not Exist');
    $ErrorDescription['1171'] = _('Incorrect Location Name Length');
    $ErrorDescription['1172'] = _('Tax Province ID Not Setup');
    $ErrorDescription['1173'] = _('Invalid Controlled');